# Generated by Django 4.0.5 on 2022-06-02 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_puppy_adoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puppy',
            name='adoption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.adoption'),
        ),
    ]
